name: Hotfix release

on:
  push:
    branches:
      - hotfix

env:
  NODE_VERSION: 16

jobs:
  lint-commits:
    name: Lint commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Get branch names
        uses: tj-actions/branch-names@v2.1
        id: branch-name

      - name: Get parent commit SHA
        id: parent-commit
        run: |
          git checkout --track -b ${{ github.event.repository.default_branch }} origin/${{ github.event.repository.default_branch }}
          git checkout ${{ steps.branch-name.outputs.current_branch }}
          echo "::set-output name=sha::$(diff -u <(git rev-list --first-parent ${{ steps.branch-name.outputs.current_branch }}) <(git rev-list --first-parent ${{ github.event.repository.default_branch }}) | sed -ne 's/^ //p' | head -1)"

      - name: Install modules
        run: yarn --frozen-lockfile

      - name: Lint
        run: yarn commitlint --from ${{ steps.parent-commit.outputs.sha }} --to ${{ github.SHA }} --verbose

  lint-code:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install modules
        run: yarn --frozen-lockfile

      - name: Lint
        run: yarn lint:code

  lint-type:
    name: Type checking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install modules
        run: yarn --frozen-lockfile

      - name: Run typescript check
        run: yarn lint:type

  test-build:
    name: Build testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install modules
        run: yarn --frozen-lockfile

      - name: Build the app
        run: yarn build

  release:
    name: 🚀 Release
    needs: [lint-commits, lint-type, test-build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Semantic release
        uses: cycjimmy/semantic-release-action@v2
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          semantic_version: 18.0.0
          branches: |
            [
              {
                name: 'hotfix',
                prerelease: true,
              },
            ]
          extra_plugins: |
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
            @semantic-release/github
            conventional-changelog-conventionalcommits@4.6.1
